--CREATE TABLE addressEntity (
--id SERIAL PRIMARY KEY,
--name TEXT NOT NULL,
--number INTEGER NOT NULL,
--postalCode TEXT NOT NULL,
--city TEXT NOT NULL,
--continent TEXT NOT NULL,
--addressEntity_id INTEGER NOT NULL,
--FOREIGN KEY (hotel_id) REFERENCES hotel(id)
--);
--
--CREATE TABLE airportEntity (
--id SERIAL PRIMARY KEY,
--name TEXT NOT NULL,
--);
--
--
---- -----------------------------------------------------
---- Schema full-stack-ecommerce
---- -----------------------------------------------------
--DROP SCHEMA IF EXISTS `full-stack-ecommerce`;
--CREATE SCHEMA `full-stack-ecommerce`;
--USE `full-stack-ecommerce` ;
--alter table offer
--add promoted BIT DEFAULT 1;
---- -----------------------------------------------------
---- Table `full-stack-ecommerce`.`product_category`
---- -----------------------------------------------------
--CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`offer_category` (
--  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
--  `category_name` VARCHAR(255) NULL DEFAULT NULL,
--  PRIMARY KEY (`id`))
--ENGINE=InnoDB
--AUTO_INCREMENT = 1;
---- -----------------------------------------------------
---- Table `full-stack-ecommerce`.`product`
---- -----------------------------------------------------
--CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`offer` (
--  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
--  `sku` VARCHAR(255) DEFAULT NULL,
--  `name` VARCHAR(255) DEFAULT NULL,
--  `description` VARCHAR(255) DEFAULT NULL,
--  `unit_price` DECIMAL(13,2) DEFAULT NULL,
--  `image_url` VARCHAR(255) DEFAULT NULL,
--  `active` BIT DEFAULT 1,
--  `units_in_stock` INT(11) DEFAULT NULL,
--   `date_created` DATETIME(6) DEFAULT NULL,
--  `last_updated` DATETIME(6) DEFAULT NULL,
--  `category_id` BIGINT(20) NOT NULL,
--  PRIMARY KEY (`id`),
--  KEY `fk_category` (`category_id`),
--  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `offer_category` (`id`)
--)
--ENGINE=InnoDB
--AUTO_INCREMENT = 1;
--SELECT * FROM offer_category;
--SELECT * FROM offer;
--ALTER TABLE offer
--add last_minute BIT DEFAULT 1;
--UPDATE table_name
--SET column1 = new_value1, column2 = new_value2, ...
--WHERE condition;
--DELETE FROM offer_category
--WHERE category_name = 'excursion';
--
--
